### ISSUE TITLE
compatibility issues

### ISSUE THREAD

**Issue by ghost** [ssmit1986/BayesianInference#13]
Hi,

Thanks for your nice code.

I've seen your code comes with an example notebook "Bayesian Nested...." At the very end, you explore some bayesian neural networks approach. 

In the attempt to run them I receive a lot of: 

"ConstantArrayLayer is deprecated and will not be supported in future \
versions of the Wolfram Language. Use NetArrayLayer instead"

and 

"NetInformation is obsolete. Instead, use Information."

...probably it is not at all an issue (but I am totally inexpert to read the outputted numbers and to understand if they make sense) but I was wondering if you have an up to date example file, or if you plan to update that wrapper to the most recent Mathematica release (I'm currently running ver 13).

Thanks in advance for your attention!

**Comment by ssmit1986** [comment]
Hello!

Thanks for your interest in my repository. Yes, I've had this happen a couple of times with neural networks. The developments of the NN functionality in WL are going very rapidly and between versions this often means that old code might start throwing errors or stop working once you move to the next version of WL. If it works, it works though. You can just quiet it for now; I'll see when I have time to fix these things.

Thank you for letting me know!
Sjoerd

**Comment by ghost** [comment]
ThX
