### ISSUE TITLE
Regression with WeightedData

### ISSUE THREAD

**Issue by ghost** [ssmit1986/BayesianInference#14]
Hi 

Thanks for your nice code.

I was looking at one example you report in your examples-file to do the regression with nested-sampling:

```
BlockRandom[
 SeedRandom[1];
 testdata = (# -> (# + 2 RandomReal[])) & /@ RandomReal[{-1, 1}, 20];
 ]

obj = defineInferenceProblem[
  "Data" -> testdata,
  "GeneratingDistribution" -> NormalDistribution[
    a x + b,
    sigma
    ],
  "Parameters" -> {{a, -10, 10}, {b, -10, 10}, {sigma, 0.1, 10}},
  "IndependentVariables" -> {x},
  "PriorDistribution" -> {"LocationParameter", "LocationParameter", 
    "ScaleParameter"}
  ]

result = nestedSampling[obj]
```

How should I change it to add some weights on the starting data? E.g., how can I use Mathematica's WeightedData? Or in general, all real data in Physics come with errors. How can I include them in a regression process?

Thank you in advance for your kind help!

**Comment by ssmit1986** [comment]
Hello,

Due to family circumstances, I am unable to help you right now. I'll get
back to you when I'm back in the office.

Thank you for understanding,
Sjoerd

**Comment by ghost** [comment]
Hi,

I hope everything is solved for the best for you!
I found my way to the problem and I can close this issue.

All the best.

MyLiit
