### ISSUE TITLE
Fitting with time series processes

### ISSUE THREAD

**Issue by YetAnotherDima** [ssmit1986/BayesianInference#4]
In "example_code.nb" for "Fitting with time series processes" you use this block: 
With[{mu = 0, logsigma = -4},
 Print@obj["LogLikelihoodFunction"][{mu, logsigma}];
 Print@LogLikelihood[
   GeometricBrownianMotionProcess[mu, Exp[logsigma], start], ts]
 ]

Why you use logsigma = -4?

**Comment by ssmit1986** [comment]
Hi, Dima,

That block of code is just for the purpose of illustrating that the likelihood function defined in that example isn't the same as the one computed by using: 

    LogLikelihood[GeometricBrownianMotionProcess[...], ...]

That particular section is just an introduction to time series modelling. The model defined by using `"GeneratingDistribution" -> process[t]` assumes that all observations in the time series are independent, which is obviously not very realistic. The value of `logsigma = -4` is just to illustrate that the two log-likelihoods are different; nothing else. It could've been any number, really.

**Comment by YetAnotherDima** [comment]
Thank you
