### ISSUE TITLE
Use BayesianInference

### ISSUE THREAD

**Issue by YetAnotherDima** [ssmit1986/BayesianInference#5]
Hi Sjoerd,

I have a few questions. Please let me know as I could not find your email and there is no DM option here. my email: yetanotherdmitry@gmail.com

Regards,
Dima

**Comment by ssmit1986** [comment]
Hi Dima,

I don't believe there is a direct messaging option here, as far as I'm aware. Feel free to post your questions on this thread or add me on LinkedIn (which does have chat functions):
https://www.linkedin.com/in/sjoerd-smit-59b44339/

If you have another suggestion for how you want to contact me, just let me know.

I'm a bit busy in the next few days, so I may not be able to make time for a chat for a bit, but I'll try.

Best,
Sjoerd

**Comment by YetAnotherDima** [comment]
Thanks. I sent you a message.
